use hackerrank;
select * from occupations;


SELECT 
MAX(CASE WHEN OCCUPATION = "DOCTOR" THEN NAME END) AS DOCTOR,
MAX(CASE WHEN OCCUPATION = "Professor" THEN NAME END) AS Professor,
MAX(CASE WHEN OCCUPATION = "SINGER" THEN NAME END) AS Singer,
MAX(CASE WHEN OCCUPATION = "ACTOR" THEN NAME END) AS ACTOR
FROM (
	SELECT NAME, OCCUPATION, ROW_NUMBER() OVER(PARTITION BY OCCUPATION ORDER BY NAME) AS ROW_NUM 
	FROM OCCUPATIONS
    ) AS TEMP
GROUP BY ROW_NUM;